name: netcdf-4.7.4
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-9
      FC: gfortran-9
      CXX: g++-9
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]
        compiler: [gcc-9]      

    steps:
    - name: cache-mpich
      id: cache-mpich
      uses: actions/cache@v2
      with:
        path: ~/mpich
        key: mpich-${{ runner.os }}-3.3.2-1

    - name: build-mpich
      if: steps.cache-mpich.outputs.cache-hit != 'true'
      run: |
        if [[ ${{ matrix.os }} == "macos-10.15" ]]; then
          wget http://www.mpich.org/static/downloads/3.3.2/mpich-3.3.2.tar.gz &> /dev/null
          tar -xzf mpich-3.3.2.tar.gz
          pushd mpich-3.3.2
          ./configure --prefix=$HOME/mpich
          make
          sudo make install
          popd
        fi

    - name: install-dependencies
      run: |
        echo "/home/runner/mpich/bin" >> $GITHUB_PATH
        if [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then
          sudo apt-get update
          sudo apt-get install libmpich-dev
          sudo apt-get install doxygen
          sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config
          sudo apt-get install libpng-dev
          sudo apt-get install libjpeg-dev
        elif [[ ${{ matrix.os }} == "macos-10.15" ]]; then
          echo "$HOME/mpich/bin" >> $GITHUB_PATH
          brew update
          brew install doxygen
          brew install mpich
          brew install netcdf
          brew install wget
          if [[ ${{ matrix.compiler }} == "gcc-9" ]]; then
            sudo ln -sf /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          elif  [[ ${{ matrix.compiler }} == "gcc-10" ]]; then
            sudo ln -sf /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
          fi
        fi
        python3 -m pip install gcovr

    - name: cache-esmf
      id: cache-esmf
      uses: actions/cache@v2
      with:
        path: ~/esmf
        key: esmf-${{ runner.os }}-8.0.1-2

    - name: build-esmf
      if: steps.cache-esmf.outputs.cache-hit != 'true'
      run: |
        set -x
        pushd ~
        export ESMF_DIR=~/esmf-ESMF_8_0_1
        wget https://github.com/esmf-org/esmf/archive/ESMF_8_0_1.tar.gz &> /dev/null && ls -l
        tar zxf ESMF_8_0_1.tar.gz && ls -l
        cd esmf-ESMF_8_0_1
        export ESMF_COMM=mpich3
        export ESMF_INSTALL_BINDIR=bin
        export ESMF_INSTALL_LIBDIR=lib
        export ESMF_INSTALL_MODDIR=mod
        export ESMF_COMPILER=gfortran
        export ESMF_INSTALL_PREFIX=~/esmf
        export ESMF_NETCDF=split
        if [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then 
          export ESMF_NETCDF_INCLUDE=/usr/include
          export ESMF_NETCDF_LIBPATH=/usr/x86_64-linux-gnu
        elif [[ ${{ matrix.os }} == "macos-10.15" ]]; then
          export ESMF_NETCDF_INCLUDE=/usr/local/include
          export ESMF_NETCDF_LIBPATH=/usr/local/lib
        fi
        make -j2
        make install

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/jasper
        key: jasper-${{ runner.os }}-2.0.22

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        set -x
        pwd
        wget https://github.com/jasper-software/jasper/archive/version-2.0.22.tar.gz &> /dev/null && ls -l
        tar zxf version-2.0.22.tar.gz && ls -l
        cd jasper-version-2.0.22
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/jasper
        make -j2
        make install

    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ${HOME}/hdf5
        key: hdf5-${{ runner.os }}-1.10.7-1

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        export CC=mpicc
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7.tar.gz &> /dev/null
        tar -xzf hdf5-1.10.7.tar.gz
        pushd hdf5-1.10.7
        ./configure --prefix=${HOME}/hdf5 --enable-parallel --disable-tools --disable-fortran --disable-cxx --enable-parallel-tests
        make
        sudo make install
        popd
        ls -l ${HOME}/hdf5
          
    - name: cache-netcdf-c
      id: cache-netcdf-c
      uses: actions/cache@v2
      with:
        path: ~/netcdf-c
        key: netcdf-c-${{ runner.os }}-4.7.4

    - name: build-netcdf-c
      if: steps.cache-netcdf-c.outputs.cache-hit != 'true'
      run: |
        set -x
        ls -l ${HOME}/hdf5
        export CC=mpicc
        export CPPFLAGS=-I${HOME}/hdf5/include
        export LDFLAGS=-L${HOME}/hdf5/lib
        wget https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.7.4.tar.gz &> /dev/null
        tar -xzf netcdf-c-4.7.4.tar.gz
        pushd netcdf-c-4.7.4
        ./configure --prefix=${HOME}/netcdf-c --disable-dap --disable-utilities
        make -j
        sudo make install
        popd

    - name: cache-netcdf-fortran
      id: cache-netcdf-fortran
      uses: actions/cache@v2
      with:
        path: ~/netcdf-fortran
        key: netcdf-fortran-${{ runner.os }}-4.5.3-mpich-3.3.2-2

    - name: build-netcdf-fortran
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        set -x
        export CC=mpicc
        export FC=mpifort
        export CPPFLAGS=-I${HOME}/netcdf-c/include
        export LDFLAGS=-L${HOME}/netcdf-c/lib
        wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz &> /dev/null
        tar -xzf v4.5.3.tar.gz
        pushd netcdf-fortran-4.5.3
        ./configure --prefix=/home/runner/netcdf-fortran
        make -j
        sudo make install
        popd

    - name: checkout-nceplibs
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS
        path: nceplibs

    - name: get-git-hash
      run: |
        cd nceplibs
        git rev-parse HEAD > hash.txt
        
    - name: cache-nceplibs-develop
      id: cache-nceplibs-develop
      uses: actions/cache@v2
      with:
        path: ~/nceplibs
        key: nceplibs-develop-${{ runner.os }}-${{ hashFiles('nceplibs/hash.txt') }}

    - name: build-nceplibs
      if: steps.cache-nceplibs-develop.outputs.cache-hit != 'true'
      run: |
        set -x
        export ESMFMKFILE=~/esmf/lib/esmf.mk
        cd nceplibs
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH='~;~/jasper' -DCMAKE_INSTALL_PREFIX='~/nceplibs' -DFLAT=ON
        make -j2
       
    - name: checkout-ufs-utils
      uses: actions/checkout@v2
      with: 
        path: ufs_utils

    - name: build-ufs-utils
      run: |
        export ESMFMKFILE=~/esmf/lib/esmf.mk
        cd ufs_utils
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH='~/jasper;~/nceplibs' -DENABLE_DOCS=On -DCMAKE_Fortran_FLAGS="-g -fprofile-arcs -ftest-coverage -O0"
        make -j2
        make test
        export PATH="/home/runner/.local/bin:$PATH"
        gcovr -r .. --html-details -o test-coverage.html

    - uses: actions/upload-artifact@v2
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      with:
        name: test-coverage
        path: ufs_utils/build/*.html
